from enum import StrEnum


class Role(StrEnum):
    CLIENT_OWNER = "client_owner"
    CLIENT_MEMBER = "client_member"
    STUDENT = "student"
    TECHNICAL_LEAD = "technical_lead"
    REVIEWER = "reviewer"
    COORDINATOR = "coordinator"
    UNIVERSITY_VIEWER = "university_viewer"
    PLATFORM_ADMIN = "platform_admin"


class ProjectState(StrEnum):
    DRAFT = "DRAFT"
    SCOPING = "SCOPING"
    AWAITING_COORDINATOR_SCOPE_APPROVAL = "AWAITING_COORDINATOR_SCOPE_APPROVAL"
    AWAITING_CLIENT_SCOPE_APPROVAL = "AWAITING_CLIENT_SCOPE_APPROVAL"
    AWAITING_DEPOSIT = "AWAITING_DEPOSIT"
    STAFFING = "STAFFING"
    AWAITING_STAFFING_APPROVAL = "AWAITING_STAFFING_APPROVAL"
    AWAITING_STUDENT_ACCEPTANCE = "AWAITING_STUDENT_ACCEPTANCE"
    READY_TO_START = "READY_TO_START"
    ACTIVE = "ACTIVE"
    QA_REVIEW = "QA_REVIEW"
    AWAITING_RELEASE_APPROVAL = "AWAITING_RELEASE_APPROVAL"
    CLIENT_REVIEW = "CLIENT_REVIEW"
    REVISION_REQUESTED = "REVISION_REQUESTED"
    CHANGE_ORDER_REVIEW = "CHANGE_ORDER_REVIEW"
    ACCEPTED = "ACCEPTED"
    PAYOUT_PENDING = "PAYOUT_PENDING"
    COMPLETED = "COMPLETED"
    PAUSED = "PAUSED"
    CANCELED = "CANCELED"
    DISPUTED = "DISPUTED"


class OfferState(StrEnum):
    DRAFT = "DRAFT"
    OFFERED = "OFFERED"
    ACCEPTED = "ACCEPTED"
    DECLINED = "DECLINED"
    EXPIRED = "EXPIRED"
    WITHDRAWN = "WITHDRAWN"


class TaskState(StrEnum):
    BACKLOG = "BACKLOG"
    READY = "READY"
    IN_PROGRESS = "IN_PROGRESS"
    BLOCKED = "BLOCKED"
    IN_REVIEW = "IN_REVIEW"
    DONE = "DONE"


class EnvironmentLabel(StrEnum):
    DEMO = "demo"
    TEST = "test"
    LIVE = "live"


class CredentialStatus(StrEnum):
    VALID = "VALID"
    REVOKED = "REVOKED"


class PublicIntakeStatus(StrEnum):
    NEW = "NEW"
    IN_REVIEW = "IN_REVIEW"
    QUALIFIED = "QUALIFIED"
    REJECTED = "REJECTED"
    CONVERTED = "CONVERTED"
